name: Atualizar Licitações

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      data_inicial:
        description: 'Data Inicial (AAAAMMDD)'
        required: false
      data_final:
        description: 'Data Final (AAAAMMDD)'
        required: false

permissions:
  contents: write

jobs:
  coletar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para o rebase funcionar

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependencias
        run: pip install requests pandas

      - name: Rodar Robo
        env:
          DATA_INICIAL: ${{ github.event.inputs.data_inicial }}
          DATA_FINAL: ${{ github.event.inputs.data_final }}
        run: python coleta_pncp.py

      - name: Salvar Dados (Anti-Conflito)
        run: |
          git config --global user.name 'Robo'
          git config --global user.email 'robo@email.com'
          git pull origin main --rebase
          git add dados.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Carga $(date +'%Y-%m-%d')"
          git push origin main
