name: Atualizar Licitações

on:
  schedule:
    - cron: '0 8 * * *' # Roda automático todo dia
  workflow_dispatch:
    inputs:
      data_inicial:
        description: 'Data Inicial (Ex: 20250101)'
        required: false
        default: ''
      data_final:
        description: 'Data Final (Ex: 20250131)'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  coletar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar
        run: pip install requests pandas
      
      - name: Rodar Robô
        env:
          DATA_INICIAL: ${{ github.event.inputs.data_inicial }}
          DATA_FINAL: ${{ github.event.inputs.data_final }}
        run: python coleta_pncp.py

    - name: Salvar Dados
        run: |
          git config --global user.name 'Robo'
          git config --global user.email 'robo@email.com'
          git pull origin main --rebase  # Isso resolve o conflito "fetch first"
          git add dados.json
          # Só faz o commit se houver mudanças reais no arquivo
          git diff --quiet && git diff --staged --quiet || git commit -m "Carga de dados $(date +'%Y-%m-%d')"
          git push origin main
